### ISSUE TITLE
태그 입력창에서 자모가 분리됩니다.

### ISSUE THREAD

**Issue by hoyajigi** [joostory/tistory-editor#1]
아무래도 electron의 버그인거 같지만 태그 입력하는 창에서 첫 글자만 자모가 분리됩니다.
예를 들어 무민을 입력하려고 하면 ㅁㅜ민으로 입력되고 티스토리를 입력하려고 하면 ㅌㅣ스토리로 입력이 됩니다.
OSX 10.11.6(15G1212) 입니다.

![2016-12-23 5 27 57](https://cloud.githubusercontent.com/assets/1335881/21449904/50eb62f2-c935-11e6-8518-fcd6357e66f3.png)

**Comment by joostory** [comment]
전체적인 디자인에 material-ui를 사용하고 있는데 label에 애니메이션이 있는 textinput에 그 문제가 있을 것 같다는 생각만 하고 있었어요.

그러고보니 저 문제를 알면서도 안고쳤네요. ;; 조만간 수정하도록 할께요.
