### ISSUE TITLE
tistory 신규 연동 불가

### ISSUE THREAD

**Issue by naudhizb** [joostory/tistory-editor#108]
신규 연동 시 callback.html이 없어 정상 진행이 불가합니다.(404)

https://joostory.net/tistory-editor/callback.html

**Comment by joostory** [comment]
@naudhizb 답이 늦었네요. 인증 후 callback url이 예전에 사용하던 것이네요. 최신버전으로 업데이트하시면 문제가 해결될 것 같습니다.
https://joostory.github.io/tistory-editor/callback.html 로 바꿨거든요.

**Comment by naudhizb** [comment]
![2023-04-17 01 35 31](https://user-images.githubusercontent.com/6000385/232327249-23e94a95-e2a0-4d77-9ea4-8054c3a9a9f0.png)
1.6.1 설치 후 실행할 때 티스토리 인증 요청 패킷들입니다. 맨 처음에는 joostory.github.io로 요청하는데 joostory.net으로 리디렉션하고 해당 주소에서 404오류를 발생시키는 것 같습니다.  remote address가 다른걸로 봐서는 별도  github 저장소인 것 같아보이는데 해당 repo에 파일이 없는 것 아닐까요?

**Comment by joostory** [comment]
;;; 죄송합니다.
이 repo 에 github pages를 설정해둬야 동작하는데 해제되어 있었네요.
joostory.github.io -> joostory.net 은 리디렉션되는게 맞습니다.
제가 제대로 확인도 안하고 답을 드렸네요. 이제 정상동작할 겁니다.

최종적으로 https://joostory.net/tistory-editor/callback.html 이 페이지에서 앱으로 연결되면 성공입니다.

**Comment by naudhizb** [comment]
감사합니다. 잘 동작하네요.
