### ISSUE TITLE
10으로 넘어오면서 조금 불안해 진것 같습니다.

### ISSUE THREAD

**Issue by gossi1701** [joostory/tistory-editor#11]
버전 10으로 넘어오면서 조금 불안한것 같습니다. (MAC version 사용)

1) 이미지 업로드 실패가 자주 뜸. 하지만 재시도 할 경우에 되는 경우가 많음
2) 포스팅 발행할 경우에 실패가 자주 뜸. 실패 시 무한 로딩 발생, 포스팅 문서 날라감

되었다가 안되었다 하는것 보니 서버의 문제 같다는 생각이 드네요.

하지만 2번의 경우에 작성한 텍스트 문서가 날라가는것이 문제인것 같아요.

  1) 무한로딩이 되지 않도록 실패 메세지만 뜨도록 개선하는것( 이미지와 동일하게 )
  2) 발행 전에 자동 저장

이 두가지 중에 하나로 개선 가능 할까요? 언제나 감사합니다.

**Comment by joostory** [comment]
'이미지 업로드 실패가 자주 뜸' 과 '포스팅 발행할 경우에 실패가 자주 뜸'는 앱의 문제라기보다는 네트웍이나 api의 문제로 보이네요.

1. 이미지 업로드 실패할 경우 왜 실패하는지 로깅해서 저에게 전달할 수 있다면 원인 파악이 좀 쉬울 것 같네요.
2. 실패할 경우 말씀하신대로 실패했다고 하고 로딩바가 사라지면 당장의 문제는 해결이 될 것 같고 임시저장은... 생각해보겠습니다.

**Comment by gossi1701** [comment]
![image](https://cloud.githubusercontent.com/assets/16268540/22862859/3f11529a-f17a-11e6-8a8c-34bc3a66ee58.png)

넵 이 로딩바만 해결이 되면 좋을것 같아요.^^

**Comment by joostory** [comment]
액션이 자주 실패하는 이유는 예상대로 api 문제였습니다. 지금은 그리 오류가 많이 나진 않을겁니다.
어쨌든 이번 기회에 오류처리를 개선하도록 하겠습니다.

**Comment by tkwlsrl** [comment]
한 2주전부터 사용하는 사용자입니다.  위 문제는 저도 한번 겪었습니다.

딱 한 번밖에 안 겪어 보았지만, 혹시나 재현 될 까봐 항상 `Ctrl + C`로 복사해 두고, `저장` 혹은 `발행`을 누릅니다. ㅎ.
이미지 붙여 넣기 기능이 되는것을 찾다가 이 프로그램을 발견했는데, 매우 잘 사용하고 있습니다. ^_^ 감사합니다. 덕분에 먼지쌓인 블로그에, 글 쓰는 횟수가 늘었습니다.

앞으로도 잘 부탁드립니다. ^_^

**Comment by joostory** [comment]
이 문제에 대한 개선은 [0.2.13](https://github.com/joostory/tistory-editor/releases/tag/0.2.13) 버전을 통해서 어느 정도 해결된 것 같습니다.
