### ISSUE TITLE
태그 입력이 종종 안됩니다.

### ISSUE THREAD

**Issue by junho85** [joostory/tistory-editor#13]
![image](https://cloud.githubusercontent.com/assets/1219373/24151123/28725902-0e8b-11e7-918e-fe6f79a85655.png)
태그 입력 했는데 엔터 치면 자꾸 사라지네요.

**Comment by joostory** [comment]
맥에서 한글 입력할 때 그러는데요. 다 입력한 후에 `→` 한번 눌러주시고 콤마나 엔터키 입력하심 돼요. 맥 한글 입력기가...

방법을 찾아볼께요.

**Comment by junho85** [comment]
엇? 문득 맥에서 그냥 엔터키 쳤는데 잘 입력되네요. 뭔가 개선 되었나 봅니다.

**Comment by joostory** [comment]
https://github.com/TeamWertarbyte/material-ui-chip-input/pull/124 와 같은 이슈네요. https://github.com/TeamWertarbyte/material-ui-chip-input/releases/tag/v0.15.3 에 포함되었는데요. 0.3.9 버전에서 0.16 으로 업그레이드하면서 해결된 것 같아요.

일이 바빠 신경을 못쓰고 있었는데 저절로 해결이 ㅠㅠ 죄송합니다.
