### ISSUE TITLE
블로그의 이름의 길이가 왼쪽 사이드바의 길이보다 길 때 "새 글 버튼"을 클릭 할 수 없는 문제

### ISSUE THREAD

**Issue by koesnoom** [joostory/tistory-editor#14]
블로그의 이름의 길이가 왼쪽 사이드바의 길이보다 길 때 "새 글 버튼"을 클릭 할 수 없는 문제

제목 그대로 블로그의 제목이 길어서 범위를 넘어서면 새글쓰기 버튼을 클릭할 수 없습니다.
좌측 사이드바의 너비를 조절 할 수 있도록 수정하면 좋을 것 같습니다.

환경은 mac입니다.
타 환경에서는 테스트하지 못하였습니다.

**Comment by joostory** [comment]
@koesnoom 첫번째 pr 이라니 몹시 흥분되네요. 일단은 width를 고정해서 ui가 틀어지지 않게만 했는데 더 좋은 방법이 있을테니 언제든 pr 날려주세요. :)
