### ISSUE TITLE
티스토리 로그인 후에도 인증화면에 머무르는 이슈

### ISSUE THREAD

**Issue by koesnoom** [joostory/tistory-editor#18]
로그아웃 후 로그인을 시도하였으나 로그인되지 않음.

1. '티스토리 인증' 버튼 클릭
2. 팝업창을 통해 티스토리 로그인
3. 팝업사라졌으나 메인화면은 변동없음.

**Comment by koesnoom** [comment]
Log를 보니 tistory 인증을 할 때 (== 팝업에서 아이디 패스워드치고 로그인 버튼을 누르면) invalid_client가 뜹니다.
정확한 디버깅이 안되서 정확히 확인은 못했지만 티스토리 클라이언트 등록한 앱의 설정이 변경되었거나 티스토리 API에서 오류를 보내는 것 같습니다. (확실하지 않은 추측이니 참고만 하시기 바랍니다)

**Comment by joostory** [comment]
@koesnoom client_id, secret_key를 안넣고 빌드를 했네요. 다시 업로드 했습니다. ㅠ

**Comment by NaniteFactory** [comment]
저도 그래요 빌드해서 실행시켰는데 로그인해도 진행이 안 되고 콘솔에 invalid_client 한 줄만 찍혀요 해결할 수 있을까요
