### ISSUE TITLE
Preference 변경이 지속되지 않음

### ISSUE THREAD

**Issue by koesnoom** [joostory/tistory-editor#19]
Preference 변경이 지속되지 않음

Editmode를 변경하였을 때 다음 수정때도 반영되었으면 합니다. 이와 관련하여 redux persist(https://github.com/rt2zz/redux-persist)를 사용해서 코드 수정을 할까합니다.

답변 부탁드립니다.

**Comment by joostory** [comment]
에디터 내에서 에디터 모드를 변경할때는 저장하지 않고 component의 state로만 값을 가지고 있습니다.
![tistory-editor-editormode](https://cloud.githubusercontent.com/assets/830864/26564508/8df7c542-451c-11e7-857a-398982b47cf9.png)

환경설정에서는 값을 선택하면 electron-storage를 통해서 값을 저장합니다.
![tistory-editor-preference](https://cloud.githubusercontent.com/assets/830864/26564510/955d267e-451c-11e7-9ac1-453b715d281a.png)

에디터 내에서 변경한 값의 저장을 말씀하시는 거라면 환경설정이랑 동일하게 처리하면 될 것 같아요. 이 부분은 저도 고민하다가 저장하지 않았는데요. 저장해도 괜찮다고 생각합니다. redux-persist는 localStorage에 저장하는건가요? 오~ 오늘도 좋은 거 하나 배웁니다. :)

**Comment by koesnoom** [comment]
아 환경에서 설정하는 부분이 있었네요. 확인이 제대로 안됐습니다.
