### ISSUE TITLE
0.3.3 about 창 닫으면 오류 발생

### ISSUE THREAD

**Issue by junho85** [joostory/tistory-editor#20]
![image](https://cloud.githubusercontent.com/assets/1219373/26773072/6843055e-4a04-11e7-8051-387d6e03be26.png)

**Comment by joostory** [comment]
모듈 upgrade를 막 했더니 뭐가 바뀐게 있나봐요. 흑 ㅠ

**Comment by joostory** [comment]
0.3.4 에서 해결했습니다.

**Comment by junho85** [comment]
오오 대박 빠른 패치!
