### ISSUE TITLE
File 첨부기능

### ISSUE THREAD

**Issue by ohora23** [joostory/tistory-editor#22]
File 첨부 기능의 경우, 구현이 가능할런지요? 이미지크기 조정과 File첨부만 된다면 Oneline Editor를 아예 안쓰고도 활용이 가능할 것 같아서요.

고려 부탁드립니다.

그리고, 감사드립니다.^_^

**Comment by joostory** [comment]
제가 이건 좀 불친절하게 만든 것 같긴 한데요 ;; 이미지 첨부할 수 있는 방법은 두가지가 있어요.

첫번째는 drag and drop 이에요. 이미지 파일 끌어다가 넣으시면 업로드가 되는데... 된다는 말도 없고 메시지도 자세히 나오지 않아서 모르는 상태에서는 된다고 생각하기 어렵겠네요 ;;;

두번째는 clipboard 붙여넣기에요. 이건 요청이 있어서 넣은 기능인데 넣고보니 꽤 편해서 저도 잘 쓰고 있습니다. 이미지 복사하기를 한 후에 Ctrl(Cmd)+c 하시면 됩니다.

조금 더 알기 쉽게 개선해볼께요.

**Comment by tkwlsrl** [comment]
클립보드에서 붙여 넣는거 완전 편하게 잘 쓰고 있습니다. ^_^

**Comment by joostory** [comment]
@ohora23 0.5.2 버전에 이미지 첨부기능 버튼을 명시적으로 넣었습니다.
혹시 이미지가 아닌 파일 첨부를 말씀하신 거라면... 음... 그건 티스토리 API 에서 허용하지 않아서 안됩니다.
