### ISSUE TITLE
글 쓸 때 "주제" 미리 지정 하기

### ISSUE THREAD

**Issue by junho85** [joostory/tistory-editor#23]
![image](https://user-images.githubusercontent.com/1219373/27010663-6dbef616-4ee4-11e7-989b-a17699ef03c3.png)
웹에디터에는 "주제" 라는 항목이 있는데 이게 선택 되어야 "공감" 기능이 활성화 되는 것 같습니다.
TistoryEditor 에서도 이걸 미리 선택 가능 할까요?
이게 안되어서 매번 글 쓰고 나서 웹에디터로 다시 열어서 "주제"를 설정 하려니 좀 불편하네요.

**Comment by joostory** [comment]
이건 API 에서 지원을 해줘야하는데요. 지원이 쉽지는 않을 것 같습니다. API에서 주제를 받으려면 주제 리스트와 코드를 먼저 앱에 전달을 해야할텐데... 음... 아무리 생각해도 그건 안될 것 같아요.

주제를 선택하지 않아도 공감버튼이 나와주는 것이 가장 좋을 것 같은데 가능한지 확인해보겠습니다.

**Comment by joostory** [comment]
주제를 선택해서 발행하지 않아도 발행한 글에는 공감버튼을 모두 표시할 수는 있겠지만 api에서 주제를 선택해서 발행을 하는 것은 불가한 것으로 결론내렸습니다.
