### ISSUE TITLE
brew cask search

### ISSUE THREAD

**Issue by pareut** [joostory/tistory-editor#25]
좋은 에디터 만들어주셔서 감사합니다
맥버전의 경우 brew 라는 패키지 관리 프로그램에서도 쉽게 다운로드 및 설치 해줄수 있는 커맨드라인이 존재합니다
누구나 쉽게 brew를 통해 tistory-editor을 다운로드 받을 수 있게 하려고 하는데
다운로드 경로는 무조건 joostory님의 repository 링크를 따라 갑니다
https://github.com/joostory/tistory-editor/releases/download/x.x.x/TistoryEditor-x.x.x-mac.zip

앱명은 항상  > TistoryEditor.app,
다운로드 zip 파일명은 > TistoryEditor-0.x.x-mac.zip

이런식으로 유지해주시면 좋겠네요 부탁드리겠습니다 감사합니다

**Comment by pareut** [comment]
https://github.com/caskroom/homebrew-cask/pull/36923
해당 homebrew-cask에 pull request 요청했네요
merge 이후로부터는 brew cask에서도 다운로드 가능합니다
문제가 된다면 생각하시면 코멘트 주세요

**Comment by joostory** [comment]
brew에 cask 로 앱설치를 할 수 있는 걸 오늘 알았네요. 감사합니다.
