### ISSUE TITLE
<> 기호를 사용한 텍스트

### ISSUE THREAD

**Issue by StrugglingBob** [joostory/tistory-editor#26]
안녕하세요.

오늘 설치해서 보고 있는데 상당히 편리한 것 같네요.
2가지 질문이 있습니다.

1. 글을 수정하거나 쓸 때 Markdown Editor가 아닌 다른 Editor를 Default로 지정할 수 있나요?
제가 컴퓨터를 잘하는 사람은 아니라서 Rich Editor (Tinymce)가 사용하기 더 편한 것 같은데, 수정이나 글쓰기 버튼을 누르면 Default Editor가 Markdown Editor로 되네요.

2. 티스토리 웹에서 쓴 글이 있는데, 이걸 Tistory Editor에서 수정하기 버튼을 누르고 Markdown Editor에서 Rich Editor (Tinymce)로 변경하니 텍스트가 사라지는 경우가 발생합니다.

<transit> 이라고 쓰고 위와 같이 Markdown Editor에서 Rick Editor로 변경하니 <transit>이라고 쓴 부분이 보이질 않습니다.
혹시 수정이 가능하다면 다음 업데이트에 반영하여 주시면 감사하겠습니다.

**Comment by joostory** [comment]
1. 저도 주로 tinymce를 쓰게 되면서 기본에디터 지정기능을 만들었습니다. Mac이라면 `Cmd + ,` 이고 윈도우나 리눅스에서는 `Ctrl + ,` 를 누르면 환경설정 팝업이 나옵니다. 거기에 기본에디터를 선택할 수 있습니다.  윈도우나 리눅스에서 `Alt`키를 누르면 메뉴바가 나타나는데 거기서도 들어갈 수 있습니다.

2. 마크다운은 모든 구성요소를 표시할 수 없기 때문에 html 과 병행해서 사용합니다. 그래서 그냥 `<`나 `>`를 사용하면 html element로 처리될 수 있습니다. github도 마크다운을 사용하는 관계로 뭔가 없어졌다고 쓰셨을텐데 그 문자가 보이지를 않네요 ;; 마찬가지 이유라 생각됩니다. 꼭 그 문자를 사용하시려면 `&lgt;` 혹은 `&gt;` 를 사용하시면 됩니다. 마크다운을 이제 사용안하실테니 상관없겠지만 ㅎㅎ 일단 물어보시니 답을 했습니다.

수정이 필요한 것은 없는 것 같네요. 혹시 또 문제가 있다면 언제든 여기에 글 남겨주세요.
