### ISSUE TITLE
수정 하려고 하면 script 태그가 사라집니다.

### ISSUE THREAD

**Issue by junho85** [joostory/tistory-editor#28]
gist 등에서 소스코드를 붙여 넣을 때 script 태그를 사용해야 하는데 글 작성 할 때는 스크립트를 쓸 수 있는데 수정 하려고 하면 script 가 사라집니다.
script 가 사라지지 않았으면 좋겠습니다.

**Comment by gossi1701** [comment]
이건 저도 조금 불편했던 내용이네요. 감안하고 사용하고 있던 점 입니다.

**Comment by joostory** [comment]
markdown 에디터를 기본에디터를 사용하는 경우에만 script 태그를 유지합니다.

**Comment by junho85** [comment]
@joostory markdown 에디터를 기본에디터로 사용하고 있는데도 그렇습니다 ㅠㅠ

**Comment by joostory** [comment]
@junho85 네.. 수정을 그렇게 했다는 말이었습니다. 아직 빌드해서 배포는 안했습니다.
