### ISSUE TITLE
PostListItem.js 안에 class name 일치 되지 않음

### ISSUE THREAD

**Issue by koesnoom** [joostory/tistory-editor#30]
PostListItem.js안에 class 이름이 PostListItem으로 되어야 할 것 같은데 PostList로 되어있습니다. 수정하시면 export도 변경하셔야 합니다.

PostList.js에서 PostListItem으로 import하기 때문에 문제는 없지만 특별한 이유가 없다면 파일명과 클래스명을 맞추는게 좋을 것 같습니다.

혹시 특별한 이유가 있지 않을까 싶어 수정은 하지 않고 이슈로만 올렸습니다.

**Comment by joostory** [comment]
@koesnoom 말씀하신대로 default로 export하기 때문에 오류가 나진 않지만 이상한 이름이었습니다. 수정했습니다. 감사합니다.
