### ISSUE TITLE
붙여넣기 관련

### ISSUE THREAD

**Issue by StrugglingBob** [joostory/tistory-editor#32]
버전이 업데이트가 되었네요.

1. 현재 TinyMCE를 기본 에디터로 사용중입니다.
그런데 저만 그러는 것인지는 모르겠지만 크롬에서 웹주소를 복사하고 티스토리 에디터에서 붙여넣기를 하면 붙여넣기가 되질 않습니다.
제 컴퓨터가 이상한가 싶어서 메모장에 붙여넣기를 해보면 잘 동작합니다.
그리고 TinyMCE의 메뉴에서 링크 버튼을 누르고 주소칸에 붙여넣기를 하면 잘 동작합니다. 그런데 본문에서는 붙여넣기가 동작하지 않습니다.
그리고 TinyMCE가 아닌 Quill에서 해보면 또 붙여넣기가 잘 작동합니다.
혹시 에러가 아닌지 문의 드립니다.

2. 크롬을 보면 붙여넣기를 할 때 서식을 빼고 Text로 붙여넣는 메뉴가 있습니다.
혹시 티스토리 에디터에도 그런 기능이 있는지 궁금합니다.
지금은 임시방편으로 메모장에 붙여넣기를 하고 다시 티스토리 에디터로 붙여넣기를 하고는 있습니다만 혹시 해당 기능이 있으면 좋을 것 같습니다.

**Comment by joostory** [comment]
이미지 붙여넣기를 하느라 텍스트 붙여넣기에 조금 매끄럽지 않은 부분이 있었네요.
텍스트 붙여넣기가 전혀 안되는 건 이미지 붙여넣기 초기버전에 그랬던건데 아마 문제가 되는 버전을 쓰고 계신 것 같습니다. 되긴할건데 조금.. 이상할 뿐 ;;;

어쨌건 지금버전이 0.3.9인데요. 0.3.10에서는 잘 될 겁니다. 빌드는 곧 하도록 하겠습니다.
