### ISSUE TITLE
내용없이 저장 한 경우 뺑뺑이가 사라지지 않습니다

### ISSUE THREAD

**Issue by junho85** [joostory/tistory-editor#33]
내용없이 저장 하고 해당 글을 TistoryEditor 에서 열어 보면 뺑뺑이가 계속 돌고 있습니다.
![image](https://user-images.githubusercontent.com/1219373/31062722-c5053760-a767-11e7-8cfc-3ce0591859a1.png)

아직 작성한 내용이 없다고 나타나는게 좋겠습니다.

**Comment by joostory** [comment]
완료처리를 content 유무로 했나부네요. ;; 고.. 곧 수정하겠습니다. pr 해주시면 더 좋고 ㅎㅎ

**Comment by joostory** [comment]
0.5 버전에서 해결되었습니다.
