### ISSUE TITLE
0.4.0 버전에서 티스토리 인증이 안됩니다.

### ISSUE THREAD

**Issue by artanis0** [joostory/tistory-editor#34]
https://joostory.github.io/tistory-editor/에서 0.4.0버전으로 로그인까지 완료하였지만, 계속 티스토리 인증창만 보입니다.

윈도우 10이고, 메일 인증까지 완료해서 로그인하면 로그인창은 사라지고 인증 화면에서 계속 머물러 있는 현상입니다.

**Comment by joostory** [comment]
하아.. ㅠㅠ 매번 하던 실수를 또 했네요. 오랜만에 업데이트하다보니 확인하는 걸 잊었습니다. 죄송합니다.
방금 업로드된 파일 수정했어요. 다시 다운로드 받으시면 될겁니다.
