### ISSUE TITLE
티스토리 페이지 작성된 글을 수정하면 글관리로 갑니다.

### ISSUE THREAD

**Issue by iamhoya** [joostory/tistory-editor#37]
페이지 내용 수정할 경우 페이지로 저장되게 했으면 좋겠습니다.

**Comment by joostory** [comment]
티스토리 api는 글만 등록,수정이 가능한 것으로 알고 있습니다. 페이지가 나오는 것은 api의 버그이구요. api가 수정되면 앱에서는 더이상 보이지 않게 될거라 생각합니다.
