### ISSUE TITLE
auto link

### ISSUE THREAD

**Issue by Terrorboy** [joostory/tistory-editor#38]
자동링크 기능 끌 수없나요?

```
http://localhost:4000/index.php?id=zz3&a=5&b=2
```
처럼 url에 자동으로 링크가 걸리네요 ㅠ,ㅠ

ps. 확인 해보니 html이 섞였을경우 자동으로 링크가 걸리네요.

**Comment by joostory** [comment]
자동링크는 역시 marked 라이브러리에서 gfm을 기본으로 따르기 때문인데요. (https://github.com/chjj/marked#gfm) 아무래도 많은 사람들이 쓰는 github의 경험을 제공하고자 하는 것 같습니다. 티스토리 에디터도 github의 경험을 제공하는 것이 좋을 것 같아 이 옵션을 빼지않고 사용하고 있는데요. 개별로 끄는 기능을 제공하는 것은 어려울 것 같고 gfm같은 것 자체를 옵션으로 제공하는 건 고려해보도록 할께요.

역시 pr 환영합니다.

**Comment by Terrorboy** [comment]
@joostory 답변감사합니다 ㅎㅎㅎ
