### ISSUE TITLE
마크다운으로 작성 후 다시 수정 시

### ISSUE THREAD

**Issue by Terrorboy** [joostory/tistory-editor#39]
![1](https://user-images.githubusercontent.com/5427199/32709301-a7c1806a-c872-11e7-825f-e96aa87a1944.png)
위와 같이 입력  저장 후
다시 이를 수정 했을경우

![2](https://user-images.githubusercontent.com/5427199/32709308-ba93331e-c872-11e7-943c-158bf1e930aa.png)
이미지처럼 적용한 문법이 사라지네요.

한가지 방안으로는 내부에서 md파일을 생성해 따로 가지고 있는 방법도 좋을듯합니다.

**Comment by joostory** [comment]
티스토리 에디터에서 마크다운을 사용하여 글을 작성하고 수정하는 과정은 다음과 같은데요.

1. 사용자가 mardown으로 작성
2. 에디터가 html로 변환하여 서버에 전송
3. 에디터가 서버로부터 html을 수신
4. 에디터가 html을 markdown으로 변환하여 표시

말씀하신 문제는 4에서 에디터가 변환하는 방식이 사용자가 작성하는 방식과 다른 경우입니다. 아시다시피 마크다운에는 여러가지 표현방식이 존재하는데요. 코드블럭의 경우 ``` 를 사용해도 되지만 tab을 사용해도 됩니다. 현재 세팅은 사용하는 라이브러리인 `to-markdown`이 제공하는 것을 그대로 사용하고 있구요. 나중에 옵션을 줄 수 있도록 개선해보도록 할께요.

혹시 해결 가능하시다면 pr 해주신다면 좋겠습니다. :)

**Comment by Terrorboy** [comment]
@joostory 아 내용을 다시 티스토리로 부터 수신 후 다시 변환 하는군요!
일단 이슈는 닫겠습니다.~(실력이 없어 pr까지는 무리라 ㅎㅎ)
