### ISSUE TITLE
여러 이미지 업로드시 등록 방식

### ISSUE THREAD

**Issue by jjw22new** [joostory/tistory-editor#4]
안녕하세요

먼저 좋은 프로그램에 감사드립니다.

저도 Electron을 배워서 빨리 기여하고 싶네요.

여러 이미지 업로드시 현재

`![](http://cfile21.uf.tistory.com/image/2360D346586DAE9D2B18F4)![]   (http://cfile8.uf.tistory.com/image/2754FB45586DAE9E3113F5)![](http://cfile10.uf.tistory.com/image/212ABF44586DAE9E030C3C)![](http://cfile7.uf.tistory.com/image/23118940586DAE9E0E3641)![]`

이런식으로 다닥다닥 붙어서 업로드가 되는데

사실 블로그를 하면서 이미지를 양옆으로 나열하는 경우는 거의 없는걸로 알고 있습니다.
(아마 없다고 추정합니다)

보통은

```
이미지
글
이미지
글
```

이런 형태가 많으니 이미지 멀티 업로드시

```
![](http://cfile21.uf.tistory.com/image/2360D346586DAE9D2B18F4)

![](http://cfile8.uf.tistory.com/image/2754FB45586DAE9E3113F5)

![](http://cfile10.uf.tistory.com/image/212ABF44586DAE9E030C3C)

![](http://cfile7.uf.tistory.com/image/23118940586DAE9E0E3641)
```

이런 방법으로 고려해보시는게 어떠한가 합니다.

**Comment by joostory** [comment]
@jjw22new 말씀하신대로 이미지 뒤에 newline 두개씩 넣었습니다. 0.2.6 버전부터 적용됩니다.

그런데 '이미지-글-이미지-글' 이런식으로 쓸 때는 이미지 미리보기가 안되기때문에 하나씩 업로드하는 편이 더 편할 것 같습니다.
