### ISSUE TITLE
글이 하나도 없을 때는 하얀 화면만 나오네요

### ISSUE THREAD

**Issue by sklee385** [joostory/tistory-editor#43]
글이 하나도 없을때 하얀 화면만 나오고 
좌측 메뉴는 안나와서 동작 안하는 줄 알았네요 

![image](https://user-images.githubusercontent.com/4037808/33265726-198c5d2a-d3b6-11e7-92de-d50014ed431f.png)

**Comment by joostory** [comment]
이거 버그입니다. 수정은 했는데 배포를 아직 못했어요. 아마도 오늘 저녁에 할 것 같아요. 그전까진 티스토리에서 글 하나 쓰신 후에 사용하시면... ;;;

**Comment by joostory** [comment]
0.5.6 에서 해결했습니다.
