### ISSUE TITLE
현재 버전을 확인할 수 있으면 좋겠습니다.

### ISSUE THREAD

**Issue by wphestiraid** [joostory/tistory-editor#44]
현재 버전을 확인할 수 있으면 좋겠습니다.
그리고 Avast에서 설치할 때마다 차단하는데 요건 어떻게 안 될까요? 설치할 때마다 10분 정지시켜놓고 사용하는데 좀 불편해요......

**Comment by joostory** [comment]
현재 버전은 About에서 확인할 수 있어요. 새버전이 나왔다고 나오는 팝업이랑 같은 화면입니다.
앱 실행할때 아무런 팝업도 안나온다면 최신버전인 겁니다.

Avast는 안티바이러스 말씀하시는거죠? 뭐라고 나오면서 차단되는건가요? 앱 사이닝이 안되서 윈도우10에서도 설치할 때 경고가 뜨긴하는데...

**Comment by wphestiraid** [comment]
About을 평소에만 볼 수 있는 건가요?
Avast에서 차단하는 화면은 추후 업데이트 때 캡쳐해서 올려보도록 할게요...

**Comment by joostory** [comment]
윈도우에서는 Alt키를 누르면 메뉴바가 나오는데요. about은 첫번째 메뉴에 있어요.

**Comment by wphestiraid** [comment]
메뉴바가 숨겨져 있던 거군요 ㅡ,.ㅡ 감사합니다
