### ISSUE TITLE
티스토르 editor 인증시 로그인해도 무한반복되는 건 왜그런건가요? 

### ISSUE THREAD

**Issue by scotchoi** [joostory/tistory-editor#47]
로그인이 되지 않고 무한루프 돌듯 허가하기해도 다시 인증 창으로 옵니다.. 
변화가 없어요..  버그인가요?

**Comment by scotchoi** [comment]
다른기기에서는 되네요... 허참.. 왜 특정 컴터에서는 무한반복이 되는건가요? 해결하는 방법을 알려주시면 감사하겠습니다...

**Comment by joostory** [comment]
제가 앱을 빌드할때 인증정보를 잘못 설정했을때 그런 일이 좀 있었는데... 혹시 다시 다운로드 해서 설치해도 그런 일이 생기는지 확인해보세요. 다시 다운로드 받았을때 해결된다면 제가 잘못 업로드했을때 다운로드 받으신 겁니다.

;;;

**Comment by scotchoi** [comment]
알려주신대로 프로그램설치 삭제 후, 다시 설치하여 진행과 / 이전버전 (0.2.8) 로도 해봤는데.. 특정 컴터에서만 인증페이지 로그인 후 > 허가하기 클릭 > 다시 인증하기 페이지에서 변화없음인건.. 왜그런건지 궁금합니다.  컴터 설정의 문제일까요..? 바쁘시겠지만 한번 더 확인 부탁드려요!

**Comment by Hamjoon** [comment]
저도 같은 문제를 겪고 있는데요. 집 컴퓨터에서는 잘 되는데 회사 컴퓨터에서만 문제가 발생합니다. 아마도 방화벽 문제가 아닌가 싶네요. 회사 컴퓨터는 메신저 같은 외부서비스들이 대부분 막혀있거든요.

**Comment by joostory** [comment]
@Hamjoon 그런 경우라면 사용 못하겠네요.
