### ISSUE TITLE
TOAST UI Editor 추가는 어떨까요?

### ISSUE THREAD

**Issue by flynnpark** [joostory/tistory-editor#48]
https://nhnent.github.io/tui.editor/

평소에 티스토리 에디터를 잘 사용하고 있습니다. 주로 마크다운 위주로 사용하고 있는데요. 마크다운으로만 사용하려니 불편한 점이 조금씩 있더라고요. 그러던 와중에 요게 딱 보여서 혹시 적용할 수 없을까 해서 문의 드립니다!

**Comment by joostory** [comment]
이미 에디터가 codemirror, tinymce, quilljs 이렇게 3개나 붙어 있는 상황이라 더 늘리는건 좀 어려울 것 같은데... 불편하신 점을 말씀해주시면 열심히 고쳐보겠습니다.

**Comment by wphestiraid** [comment]
@joostory 저도 마음 같아서는 도와드리고 싶은데 아직 실력이 미천하여 도와드리지를 못하네요. ㅠㅠ 답변만으로도 감사합니다.
