### ISSUE TITLE
제목이 없을 때 저장 실패 메시지 발생

### ISSUE THREAD

**Issue by junho85** [joostory/tistory-editor#49]
제목 없이 작성하고 저장 하려고 하면 아래쪽에 "글을 저장하지 못했습니다" 라고 나오는데 제목이 없다고 표시 하거나 저장 팝업부터 뜨지 않도록 하는게 좋을거 같습니다.
![image](https://user-images.githubusercontent.com/1219373/36884800-6658230e-1e26-11e8-910f-b1a79346ea71.png)

**Comment by joostory** [comment]
[0.5.9](https://github.com/joostory/tistory-editor/releases/tag/v0.5.9)에 추가되었습니다.
