### ISSUE TITLE
팀블로그로 등록된 팀원이 글을 등록할 경우 글 저장이나 발행이 안되는 것 같습니다.

### ISSUE THREAD

**Issue by nicezin** [joostory/tistory-editor#5]
프로그램 너무 감사하게 잘 사용하고 있습니다. 
사용 중에 문의가 있어 글을 남겨 봅니다.

티스토리의 팀블로그를 통해 글쓰기 권한이 있는 사용자 (블로그 소유자는 아니지만 팀블로그로 초대되어 글쓰기 권한이 있는 사람)가 글을 '저장'하거나 '발행'하려 하면

"오류가 발생했습니다" 라며 글등록이 안됩니다. 소유한 블로그에는 '저장'이나 '발행'이
잘되지만, 팀블로그를 통한 글쓰기 권한을 획득한 블로그에 글을 올리면 해당 오류가 뜨는 것 같습니다.

혹시, 팀블로그 지원 업데이트도 계획에 있으신지 조심스럽게 여쭤봅니다...

**Comment by joostory** [comment]
팀 블로그로 참여하는 블로그에 글을 작성하지 못하는 문제는 티스토리 API에서 소유자만 글을 변경/작성 할 수 있도록 했기 때문입니다. 저도 관리자로 참여하는 블로그가 있는데 거기에 글이 안써지더라구요 ;;

api에서 보내주는 메시지는 소유자가 아니라서 안된다는 메시지였던 것으로 기억하는데 제가 그걸 오류가 발생했다고만 보여주도록 해놓고 고치질 않았네요. 아직 앱이 초반이라 오류메시지에 대한 처리가 불친절합니다. 이해해주세요.

이 문제는 티스토리 api 수정되면 알려드릴께요.

**Comment by joostory** [comment]
@nicezin 티스토리 api가 수정되어서 이제 됩니다.
