### ISSUE TITLE
"연결해제" 버튼 실수 누름 방지

### ISSUE THREAD

**Issue by junho85** [joostory/tistory-editor#50]
## 개요
간혹 실수로 "연결해제" 버튼을 눌러서 로그아웃 되는 경우가 있는데요.
![image](https://user-images.githubusercontent.com/1219373/37565610-989c94b4-2aef-11e8-9f08-2670d3351804.png)
"연결해제" 버튼 눌렀을 때 정말 연결해제 하는게 맞는지 확인 절차가 있었으면 좋겠습니다. 다시 로그인 하기 너무 번거롭네요 ㅠㅠ

**Comment by joostory** [comment]
[0.5.9](https://github.com/joostory/tistory-editor/releases/tag/v0.5.9)에 추가되었습니다.
