### ISSUE TITLE
멀웨어로 감지됨

### ISSUE THREAD

**Issue by NaniteFactory** [joostory/tistory-editor#51]
한 번 써 보고 싶은데 V3가 악성코드로 판단해서 실행을 차단시키네요.

정말 악성코드일 거라고 생각하지는 않지만 고쳐 주실 수 있나요.

소스코드를 받아서 `$ npm run dist`으로 앱을 만들고 실행하면 아래 같은 메시지가 뜹니다.

![default](https://user-images.githubusercontent.com/10949969/38080816-6d3fade2-337d-11e8-97d6-d7244c1728a2.PNG)

**Comment by joostory** [comment]
잘못 감지된 것 같다는 말씀 밖에는 드릴 말씀이 없네요. 직접 빌드하신다면 npm run app 으로 실행하시면 될 것 같습니다.
