### ISSUE TITLE
0.5.9 버전 업데이트 이후 사용자 정보를 불러오지 못합니다.

### ISSUE THREAD

**Issue by wphestiraid** [joostory/tistory-editor#52]
삭제 후 재설치까지 해봤는데 안 되는 것 같아요.

**Comment by wphestiraid** [comment]
0.5.8로 다운그레이드 해도 안 되는 걸 보니 에디터 자체의 문제는 아닌 것 같기도... ㅠㅠ 내일 글 써야겠네요

**Comment by joostory** [comment]
@wphestiraid tistory api 변경의 영향입니다. 0.5.10 버전을 사용해주세요.
