### ISSUE TITLE
v0.6.5 받고 나니 새로운 버전 undefined 가 있다고 나옵니다.

### ISSUE THREAD

**Issue by junho85** [joostory/tistory-editor#54]
![image](https://user-images.githubusercontent.com/1219373/40159738-9440a520-59e5-11e8-8be8-100ebc1360a3.png)

**Comment by joostory** [comment]
새버전 확인을 github api로 변경했는데 limit에 걸린 것 같습니다.
회사같이 같은 네트웍을 사용하는 곳에서는 금방 limit에 걸리겠네요.
다음 버전부터는 버전 확인 안되면 무시하도록 변경할께요.

#53

**Comment by joostory** [comment]
시간당 60 request 가능한 api 입니다. reset을 보니까 한시간 뒤네요.
- https://developer.github.com/v3/#rate-limiting

**Comment by joostory** [comment]
0.6.6 버전 부터는 이 문제가 없습니다.
