### ISSUE TITLE
네이버 스마트 에디터처럼 가능할까요? 

### ISSUE THREAD

**Issue by wonhj12** [joostory/tistory-editor#55]
안녕하세요! 
티스토리 블로그를 운영하고 있지만 아직까지는 네이버 스마트 에디터를 더 좋아하는 블로거입니다....
예전부터 티스토리도 네이버 스마트 에디터 같은 글쓰기 환경을 가지고 있으면 좋겠다고 생각했었는데 어제 Joo님께서 만드신 티스토리 에디터를 알게되었습니다. 지금 에디터도 대단하지만 네이버 스마트 에디터와 비슷한 UI와 다양한 기능들을 가지고 있다면 좋을 것 같네요... 혹시 가능할까요?? 
좋은 에디터를 만들어 주셔서 감사합니다!

**Comment by joostory** [comment]
네이버 에디터가 지원하는 다양한 모든 기능을 제공하는 것은 어렵겠지만 필요한 기능을 말씀하시면 제공하도록 노력해보겠습니다.
