### ISSUE TITLE
에디터를 통해 업로드한 이미지에 대하여

### ISSUE THREAD

**Issue by smbslt3** [joostory/tistory-editor#56]
안녕하세요 티스토리 자체 에디터가 개선의 여지가 없어 답답하던 찰나에, 만들어주신 에디터로 잘 쓰고 있습니다. 감사합니다.

티스토리 에디터에서 드래그앤 드롭으로 이미지를 쉽게 넣을 수 있는데, 이렇게 이미지를 넣고 저장한 뒤 브라우저에서 수정하려 하면 - 두~세 이미지를 나란히 배치하고 싶은 경우 - 이미지 크기가 원본 형태로 나와서 브라우저 에디터에서 너무 크게 나옵니다.

![image](https://user-images.githubusercontent.com/41793074/43657788-c7ecb1fe-9791-11e8-928e-a45993fccbea.png)

![image](https://user-images.githubusercontent.com/41793074/43657851-ed4b4ee2-9791-11e8-8ce2-c84757791de7.png)

반대로 브라우저 에디터에서 이미지를 삽입하고, 티스토리 에디터에서 보면 보이지 않습니다. 제가 마크다운 형식으로 글을 쓰는데, 브라우저에서 이미지를 삽입하면 마크다운 구조가 아니라 html구조로 나와서 그런듯 싶기도 합니다.

![image](https://user-images.githubusercontent.com/41793074/43657712-8c94aca6-9791-11e8-8682-fd40ca660a79.png)

![image](https://user-images.githubusercontent.com/41793074/43657899-08fb58d0-9792-11e8-81b9-54240fe8784e.png)

혹시 수정이 가능할까요?

그럼 티스토리에 글 쓸맛 나는 에디터 만들어주셔서 감사합니다.
좋은 하루 되세요.

**Comment by joostory** [comment]
문제는 api 의 이미지 치환자 처리에 문제가 있습니다. 아시겠지만 티스토리에서 이미지를 비롯한 첨부미디어는 `[##_미디어_##]` 와 같이 본문에 삽입됩니다. 이를 API 에서 그대로 내려줄 수는 없으니 렌더링이 완료된 상태로 내려주게 됩니다.

```html
<span class="imageblock" style="display: inline-block; width: 820px;"><span data-url="URL?original" data-lightbox="lightbox"><img src='URL' /></span></span>
```

반대로 에디터에서 API를 통해 삽입할때는 `span`을 붙여서 보낼 수도 있고 치환자 형태로 보낼 수도 있겠지만 그렇게 보내는 것이 더 문제가 많을 수도 있기 때문에 이미지 태그 그대로를 보내게 됩니다. 이걸 티스토리에서 열어보게 되면 이미지 사이즈가 설정되어 있지 않으니 커보이는 겁니다.

이런 한계를 가지고 있는 상태에서 겪고 계신 문제를 보자면 첫번째 문제는 티스토리 다음에디터에서 이미지를 화면크기에 맞게 줄여 보여주면 해결될 문제로 보이긴 합니다. 두번째 문제는 사실 저는 겪은 적이 없는데요. 별 문제가 없는 상태라고 판단됩니다. 일시적인 문제가 아닐까 싶습니다.

api 에서의 이미지 처리에 대한 문제는 api가 먼저 개선이 되어야 하기 때문에 시간이 걸릴 것 같구요. 이미지 크기는... 한번 해결해보도록 알아보겠습니다.
