### ISSUE TITLE
Tinymce Editor에서 코드블럭 사용 시 미 적용되는 문제

### ISSUE THREAD

**Issue by JuVictor** [joostory/tistory-editor#57]
제공해주신 Editor는 너무나 잘 사용하고 있습니다. 하지만, 한가지 문제가 있어 문의드립니다. 
Tinymce Editor에서 코드블럭을 사용 시 Editor에서는 정상적으로 보이나, 블로그에서는 비정상적으로 Text만 표시가 되고 있습니다. 
어떻게 해결해야 하는지요?

추가로 Tinymce Editor를 기본으로 설정 가능한지요?

**Comment by joostory** [comment]
에디터에서의 코드블럭이 highlight되어서 보이긴 하지만 실제로는 `<pre><code> 코드 </code></pre>`로 저장됩니다. 그래서 highlight는 직접해야 합니다.
