### ISSUE TITLE
코드블럭 깨지는 현상

### ISSUE THREAD

**Issue by Tiny-Haru** [joostory/tistory-editor#58]
코드블럭을 작성 후 발행이 아닌 저장을 하고, 수정을 하면 코드블럭이 깨지는 현상을 발견했습니다. 제 생각으로는 md 문법 전체가 그러는 것 같은데, 해결 가능할까요?

**Comment by joostory** [comment]
어떻게 깨지는 건지 모르겠습니다. 겪은 적이 없어서죠. 좀 더 자세히 알려주시겠어요?

**Comment by Tiny-Haru** [comment]
만약 
```Go
package main

import "fmt"

func main() {
    fmt.Println("Hello, World!")
}
```
와 같은 코드를 입력하면, 다음 수정을 할 때에는 아래와 같이 나옵니다.

    package main

    import "fmt"
    
    func main() {
        fmt.Println("Hello, World!")
    }

**Comment by joostory** [comment]
아... ``` 로 감싼 코드가 수정할때는 탭으로 표시되는걸 말씀하신거군요.
그건 구조상 어쩔 수 없습니다. 티스토리에 마크다운 텍스트 원문을 저장하지 않고 marked를 통해 html로 변환해서 저장합니다. 마찬가지로 수정할때는 티스토리에 저장된 html을 to-markdown을 통해서 markdown으로 변환하여 에디터에 표시합니다.

그래서 마크다운의 여러 표현식 중 선호하는 표현식이 있을텐데 그것으로 변환되지 않는 경우가 있습니다. 선호하는 표현식이 아니라서 조금 불편하시겠지만 원문 저장을 하지 않아서 어쩔 수 없다는 점 이해해주시기 바랍니다.
