### ISSUE TITLE
포터블 버전이 있었으면 좋겠습니다

### ISSUE THREAD

**Issue by TetraTheta** [joostory/tistory-editor#61]
현재 Release 되고 있는 티스토리 에디터의 Windows 버전은 EXE 파일로 배포되고 있습니다. 하지만 이 EXE 파일을 실행하면 아무것도 묻지 않고 바로 appdata\local에 설치를 진행합니다.  
게다가 Uninstaller가 없어서 삭제를 원할 시 직접 시작메뉴에 등록된 바로가기와 appdata\local에 들어있는 파일들을 손수 지워야 합니다.  
  
EXE 파일을 실행할 시 로컬에 설치를 할 것인지, 포터블 버전으로 설치를 할 것인지 물어본다면 좋을것 같습니다.

**Comment by joostory** [comment]
제어판 프로그램 제거에서 제거 가능하던데 안나오나요? Win7, Win10 에선 나오던데... 포터블 버전으로 빌드가 가능하지만 일일이 복사해줘야 해서 설치버전으로만 빌드했습니다.

**Comment by TetraTheta** [comment]
제어판에서 삭제를 하는게 아니라 GeekUninstaller를 사용해서 삭제를 하는데, 이 프로그램이 새 프로그램의 탐지가 늦는것 같네요.  언인스톨러쪽은 제 성급한 판단인것 같습니다.  
  
일단은 설치파일 EXE를 7-Zip으로 열어서 내부의 app-64.7z 파일을 수동으로 추출해서 포터블처럼 쓰고는 있습니다만, 설치할때 레지스트리가 등록되는 만큼, 이런 식의 포터블은 실행시에 추가적인 레지스트리 등록이 될 수도 있어 조금 불안합니다.
