### ISSUE TITLE
HTML 편집이 가능했으면 좋겠습니다

### ISSUE THREAD

**Issue by TetraTheta** [joostory/tistory-editor#62]
티스토리에서는 [HighlightJS](https://highlightjs.org/) 같은 코드 하이라이트를 스킨에 자바스크립트를 추가함으로서 쓸 수 있습니다. 하지만 이걸 실제 글에서 쓰려면 `<pre><code class="language-css">`같이 HTML 코드를 지정해줘야 사용할 수 있습니다.  
마크다운 문법도 결국 HTML로 변환해서 전송한다고 주워들었는데, HTML 코드를 에디터 내에서 직접 편집 할 수 있었으면 좋겠습니다.

**Comment by joostory** [comment]
마크다운과 rich 에디터 모두 코드블럭을 지원합니다. highlight.js를 스킨에 삽입해두기만 하면 문제없이 변환됩니다. 저도 그렇게 쓰거든요. 혹시 highlight된 상태를 그대로 글로 저장하는 것을 원하신다면... 그건 이 에디터가 원하는 바와 다릅니다.

**Comment by TetraTheta** [comment]
코드블럭쪽은 제대로 의도한대로 작동하는 것을 확인했습니다. 다만 class는 직접 웹에서 수정해야 할거 같네요.  highlightJS가 기본적으로 코드 유형을 자동으로 감지하는 특성 때문에 코드 블럭이 제대로 보이는 것 같습니다.
HTML 태그의 세부적인 조정 면에 있어서 HTML 편집 기능은 필수는 아니지만 있으면 좋다고 생각합니다.  
  
별로 필요없다고 생각하신다면 이 이슈를 닫아도 문제 없으리라 생각합니다.

**Comment by joostory** [comment]
```
    ```javascript
    console.log('hello, world')
    ```
```

위와 같이 markdown 에디터로 입력하면 아래처럼 class가 들어갑니다.

```
<pre><code class="language-javascript">console.log('hello, world')</code></pre>
```

rich 에디터에서는 이거 처리를 안해놔서 안되는데 곧 할 예정입니다. 음... 그리고 markdown 에디터에서 html 을 입력하면 그대로 사용됩니다. 참고하세요 :)
