### ISSUE TITLE
에디터 자체의 CSS 조절이 가능하면 좋겠습니다

### ISSUE THREAD

**Issue by TetraTheta** [joostory/tistory-editor#63]
티스토리에는 여러 스킨들이 있고, 이 스킨들마다 CSS 속성이 다릅니다.  
가령 `<p>`태그 사이 간격, 문단 간격이 100%인 사람도 있을 것이고, 20px인 사람도 있을 것입니다.  하지만 티스토리 에디터를 쓸때 이러한 점을 반영할 수 없습니다.  
  
예를 들자면 실행파일이 있는 경로에 editor_style.css 파일을 추가하면 에디터가 이 CSS 파일을 읽어서 에디터 상에서 해당 CSS를 사용하게 하는 그러한 방법이 좋다고 생각합니다.  
스킨의 style.css 그대로 읽기에는 skin.html의 class까지 따져야 하므로, 에디터에서만 통하게 `.editor p`같은 식으로 따로 스타일을 적도록 하는게 현실적으로 보입니다.

**Comment by joostory** [comment]
rich 에디터에서 작성한 글은 블로그에서 작성한 스타일 그대로 보이는 것이 아닙니다. 가급적 각 요소별로 inline style을 넣지 않고 있으니 실제로 보이는 style은 블로그 스킨에서 컨트롤 해주세요. 티스토리 에디터에서 작성할 때 보이는 스타일은 문단, 제목, 인용이라는 것을 구분하는 용도로만 봐주시면 될 것 같습니다.
