### ISSUE TITLE
코드블럭 사용시 라인넘버는 어떻게 표시하나요?

### ISSUE THREAD

**Issue by mountain1062** [joostory/tistory-editor#64]
어떻게 하나요?

**Comment by joostory** [comment]
```
<pre><code>
console.log('hello, world')
</code></pre>
```

티스토리 에디터에서는 위와 같이 코드 블럭 마크업을 만드는 기능만 제공합니다. 이를 이용해서 syntax highlight 를 하는 것은 각자 스킨에서 처리해주세요. 추천하는 방법은 [highlight.js](https://highlightjs.org/) 입니다.
