### ISSUE TITLE
2명 이상의 사용자 인증문제.

### ISSUE THREAD

**Issue by JHWORLD** [joostory/tistory-editor#65]
와이프와 제가 한 컴퓨터를 동시에 사용을 합니다.
아이디를 바꾸면 인증을 새로 받아야 하는 불편함이 있더라구요.
이러한 부분이 개선이 되면 좋을것 같아요.
티스토리에서 정책적으로 막으면 어쩔수 없지만요...

**Comment by joostory** [comment]
티스토리의 정책과는 상관없이 앱이 access token을 하나만 저장해서 그런거에요. 만약 맥이나 리눅스라면 이미 기계의 인증을 별도로 분리하셨을테니 문제 없을텐데 윈도우라면 조금 다를 수 있겠네요. 여러사용자 동시사용은... 한번 고려해보도록 하겠습니다.

**Comment by joostory** [comment]
v1 에서 다중 인증기능을 추가하였습니다. 이 문제가 해결된 것 같습니다. :)
