### ISSUE TITLE
0.9.1버전 0xc000007b 오류

### ISSUE THREAD

**Issue by ghost** [joostory/tistory-editor#66]
안녕하세요. 인스톨러로 설치한 티스토리 에디터는 0xc000007b오류가 뜹니다.
운영체제는 윈도우10 PRO1809입니다.
0xc000007b오류는 운영체제가 손상되었을떼 정확히 말하면 런타임 손상시 발생되는 오류입니다.
그러나 모든 프로그램은 문제가 발생하지 않으며 티스토리 에디터에만 발생하는 것으로 보아
티스토리 에디터에 오류가 있는 것으로 보입니다.

혹시나 해서 제가 직접 npm으로 빌드 해서 실행 했을떼는 0xc000007b오류가 뜨지 않습니다.
그러나 티스토리 로그인(인증)시 아이디 비번 다 맞는데 넘어가다가 흰색 화면에서 더이상
진행되지 않습니다.
해결 부탁드립니다.

**Comment by joostory** [comment]
저는 윈도우 개발 전문가가 아니라서 그런 오류는 해결해드리기 어렵습니다.
찾아보니 dll 파일 재설치, 파일시스템 검사하라는 해결책이 제시되고 있는 것으로 보아 아마도 라이브러리 파일이 손상된 것 같습니다. 재설치를 해도 계속 문제가 된다면 설치된 에디터의 파일이 아니고 에디터가 사용하는 이미 설치된 파일이 손상된 것 같습니다.

제가 추론해볼 수 있는 것은 이 정도네요. 직접 빌드해서 사용하시려면 open api 앱을 등록하시고 oauth 정보를 oauthinfo.json 파일에 작성하신 후에 빌드하시면 사용이 가능합니다. open api를 사용하거든요.
