### ISSUE TITLE
마크다운 각주(꺽쇠링크) 문법 지원

### ISSUE THREAD

**Issue by baram204** [joostory/tistory-editor#67]
### 원하는 것

마크다운 각주 용법 지원으로, 원하는 내용에 각주를 달아서, 중복되는 내용을 손쉽게 링크 처리할 수 있게 한다.

### 현재 겪는 증상

각주를 링크로 인식 하지만

1. 각주 내용을 렌더링 하지 않고,
2. 각주 내용 중 띄어쓰기가 있다면 링크로 인식하지 않는다.

### 참조 이미지

![image](https://user-images.githubusercontent.com/11155414/52766909-1a753180-306c-11e9-9d17-b3d8d610e6e0.png)

**Comment by joostory** [comment]
markdown -> html 변환에 marked를 사용하는데요. 개발자가 지원할 생각이 없답니다.
- https://github.com/markedjs/marked/issues/714

**Comment by baram204** [comment]
표준 마크다운 문법이 아니라는 링크 내용 확인했습니다. 매우 아쉽네요.
