### ISSUE TITLE
클립보드 이미지 붙여 넣기 기능이 있으면 좋겠습니다.

### ISSUE THREAD

**Issue by junho85** [joostory/tistory-editor#7]
이미지를 캡쳐해서 에디터에 붙여 넣으면 이미지가 첨부 되는 기능이 있으면 좋겠습니다.

**Comment by joostory** [comment]
[댓글](http://blog.joostory.net/443#comment16160053)로도 이런 이야기가 있었는데 이슈를 안만들어뒀네요. ^^;; 해보도록 하겠습니다.

클립보드를 바로 서버로 보내면 될텐데 그 전에 이미지인지 검사를 하는 것만 하면 될 것 같기도 해요.

**Comment by joostory** [comment]
0.2.7 버전부터 가능합니다.
