### ISSUE TITLE
미디어 삽입시 링크 추가하고 확인 누르면 깨집니다.

### ISSUE THREAD

**Issue by mountain1062** [joostory/tistory-editor#71]
백준 문제 링크 걸면 이미지가 예전처럼 크게 나오지 않고 작게 나오며

유투브 링크 걸면 글자 깨지는거 같습니다.

**Comment by joostory** [comment]
백준 문제랑 유투브 링크에 글자라는 게 무슨 말인지 모르겠습니다. 가능하시다면 캡쳐해서 주시면 좋겠습니다.
