### ISSUE TITLE
이미지 첨부 시 오류 메시지

### ISSUE THREAD

**Issue by jakero** [joostory/tistory-editor#72]
사용환경 : 윈도우 10 Pro RS4
사용 티스토리 에디터 버전 : 0.10.0
사용 설치 파일 : TistoryEditor-0.10.0-win.exe

이미지 첨부 버튼을 사용하여 이미지 첨부 시 오류 메시지가 발생하고 첨부가 되지 않습니다.

0.9.1 버전에서는 문제없습니다.

![tistory-editor-0 10 0-error](https://user-images.githubusercontent.com/20303221/55533413-28e6dd80-56ec-11e9-8311-c4781f6db0bc.png)

**Comment by joostory** [comment]
드래그앤드랍으로만 첨부를 하다보니 이미지 첨부 버튼이 제대로 동작하는지 확인을 못했네요. 수정하도록 하겠습니다.

**Comment by joostory** [comment]
0.10.2 에서 수정되었습니다.
