### ISSUE TITLE
글 편집화면 클릭 시 파일 열기 팝업창 계속 표시되는 문제 

### ISSUE THREAD

**Issue by jakero** [joostory/tistory-editor#73]
사용환경 : 윈도우 10 Pro RS4
사용 티스토리 에디터 버전(파일 버전)  : 0.10.2.65
사용 설치 파일 : TistoryEditor-0.10.2-win.exe

글 편집화면에서 제목 입력란을 제외한 나머지 부분(메뉴 버튼, 본문 입력란)을 클릭하면 클릭할때마다 파일 열기 팝업창이 계속 표시됩니다.

**Comment by zewtion** [comment]
같은버전 같은문제 입니다

**Comment by joostory** [comment]
0.10.3 에서 해결되었습니다.
