### ISSUE TITLE
<q>를 inline이 아니라 block으로 처리합니다.

### ISSUE THREAD

**Issue by kabbala** [joostory/tistory-editor#75]
`<q>`를 inline-element가 아니라 이 아니라 block으로 처리합니다.

`<p>foo <q cite="url">bar</q> baz</p>`를

`<p>foo</p><p><q cite="url">bar</q></p><p>baz</p>`로 변환합니다.

사용한 브라우저는 Firefox 67입니다.

**Comment by joostory** [comment]
v1.1.2 에서 해결되었습니다. 하지만 수정시 무시되니 사용할 때 참고해주세요.
