### ISSUE TITLE
로그인 권한 확인 후 로그인 안되는 현상 

### ISSUE THREAD

**Issue by sklee385** [joostory/tistory-editor#79]
현재 사용중인 버전은 v.0.10.3 입니다. 

로그인 후 권한 확인을 묻는 창에서 확인 누르고 나서 동작을 
안합니다. 

사용 환경은 윈도우 10 입니다.

**Comment by gnsehfvlr** [comment]
저도 윈10이며 이현상이 일어나서 티스토리 에디터를 못쓰고 있습니다.
미치겠습니다.ㅠㅠ

- 모든 브라우저 종료 후 실행해봤는데도 안됨
- 크롬 프로그램을 삭제 해보고 실행해봣는데도 안됨
- 개인 PC임, 회사 방화벽 프로그램 그런 것 존재하지도 않음


Oauth 인증 페이지로 접속해서 허용하기 버튼 누르면 urn:xxxx <-- 이게 제대로 동작하지 않는 것 같습니다.

**Comment by gossi1701** [comment]
저도 동일한 증상입니다.
컴퓨터 초기화후에 비슷한 증상을 겪고 있네요.

**Comment by joostory** [comment]
문제를 확인하여 v0.11.2 에서 해결하였습니다.
