### ISSUE TITLE
0.2.7 인증 부분에 문제가 있는것 같습니다.

### ISSUE THREAD

**Issue by gossi1701** [joostory/tistory-editor#8]
0.2.7 버전으로 로그아웃한 뒤에 다시 로그인을 하면 티스토리 인증이 안됩니다.
0.2.1 버전은 인증이 잘 되는거 보니 서버문제는 아닌것 같습니다.

**Comment by joostory** [comment]
@gossi1701 헉! oauth2 인증 정보를 초기화해놨네요. 0.2.8을 사용해주세요.
