### ISSUE TITLE
v.1.3.0 이후발생하는 urn 관련 에러

### ISSUE THREAD

**Issue by doljae** [joostory/tistory-editor#90]
1.3.0을 포함한 최신 버전 설치 시 최초 티스토리 블로그를 등록할 때

"이 urn 링크를 열려면 새 앱이 필요합니다" 

라는 탭이 뜨는 증상이 있습니다.

1.2.3 버전으로 설치했을 때는 문제가 없습니다...

어떤 문제가 있는건가요?

======================================

임시해결법

1.2.3 버전 설치 후 정상적으로 로그인 후 블로그를 등록한 뒤,
1.3.1 버전을 설치하면 정상 작동 합니다;
원인은 잘 모르겠습니다.

**Comment by joostory** [comment]
windows에서 이 문제가 있는 것을 확인했습니다. 블로그 추가는 정상적으로 되는 것으로 확인되는데요. 추가도 안되나요?

**Comment by doljae** [comment]
제가 처음으로 설치한 버전이 1.3.1 이였는데 블로그 추가가 안되었습니다.
간헐적 증상인지 아닌지는 잘 모르겠습니다.

**Comment by joostory** [comment]
[v1.3.5](https://github.com/joostory/tistory-editor/releases/tag/v1.3.5) 에서 urn링크에 관련된 오류는 해결했습니다. 그런데 windows10 1909 버전에서는 블로그 추가가 안되고 가장 최신버전인 20H2 버전에서는 정상적으로 추가가 되고 있는 것을 발견했습니다. 우연히 1909 버전에서 2004버전으로 업데이트가 안되고 있는 pc가 있어서 발견했습니다.

이걸 해결하려면 1909버전에서 디버깅을 해야하는데... 당분간은 좀 어렵지 않나 생각합니다.

**Comment by joostory** [comment]
확인해보니 또다른 문제가 있었네요. [v1.3.6](https://github.com/joostory/tistory-editor/releases/tag/v1.3.6)에서 해결되었습니다. 이제 모든 버전에서 잘 되네요.

**Comment by doljae** [comment]
감사합니다!
