### ISSUE TITLE
폰트사이즈 css 변경 후 에디터 마크다운 기능 미작동

### ISSUE THREAD

**Issue by choigww** [joostory/tistory-editor#91]
안녕하세요.

저는 최근 티스토리에서 제공하는 [Flatinum 스킨을 적용한 티스토리 블로그](https://dancefirstsensei.tistory.com/)를 개설했습니다.

폰트와 관련하여 수정하지 않은 상태로 [마크다운 에디터를 이용해 포스팅](https://dancefirstsensei.tistory.com/entry/%EA%B8%88%EC%9C%B5-AI-%EA%B8%80%EB%A1%9C%EB%B2%8C-%ED%8A%B8%EB%A0%8C%EB%93%9C)을 작성하였고, 정상적으로 마크다운이 적용되는 것을 확인했습니다.

이후 저는 Flatinum 스킨의 기본 폰트 크기가 너무 작은 듯 느껴져, 해당 스킨의 css 파일 4-6라인에 폰트사이즈 관련 코드를 삽입하였습니다.

변경 전
```
html, body, h1, h2, h3, h4, h5, h6, p, input, button, textarea {
	font-family: 'KoPub Dotum'; font-weight: 300;
}

변경 후
html, body, h1, h2, h3, h4, h5, h6, p, input, button, textarea {
	font-family: 'KoPub Dotum'; font-weight: 300; font-size: 17px;
}
```

적용 후, 블로그에 [마크다운 에디터로 작성한 포스팅](https://dancefirstsensei.tistory.com/entry/%EA%B8%88%EC%9C%B5-AI-%EA%B8%80%EB%A1%9C%EB%B2%8C-%ED%8A%B8%EB%A0%8C%EB%93%9C)을 보니 마크다운이 해제된 상태였습니다.

정확히 말씀드리면 리스팅은 남아 있지만 #, ##를 적용하여 더 크게 보여야 할 글자들이 모두 17폰트로 고정된 상태로 출력되고 있습니다.
css를 이전으로 되돌리면 마크다운은 다시 정상 적용 됩니다.

제 css 코드가 마크다운 문법 적용 이후 덮어씌워 적용되는 것처럼 보이는데요. 해결책이 혹시 있을까요?

답변해 주시면 대단히 감사하겠습니다.
오늘도 좋은 하루 되세요.

**Comment by joostory** [comment]
안녕하세요. 이미 스킨을 변경하셔셔 말씀드리는 내용이 의미 없을 수도 있지만 혹시나 다음 번 스킨수정시에 도움이 될까하여 말씀드립니다.

```
html, body, h1, h2, h3, h4, h5, h6, p, input, button, textarea {
	font-family: 'KoPub Dotum'; font-weight: 300; font-size: 17px;
}
```
변경하신 이 내용의 의미는 `html, body, h1, h2, h3, h4, h5, h6, p, input, button, textarea` 에 해당하는 html tag 내부의 폰트크기를 17px로 변경한다는 것입니다.
그리고 마크다운에서 제목을 나타내는 `#`, `##`, `###`는 각각 `h1`, `h2`, `h3`으로 변경됩니다. 따라서 변경하신 내용에 따라 모든 텍스트가 17px로 표시된 것입니다.

전체 사이트의 폰트스타일 지정과 원하는 영역의 폰트스타일 지정을 하는 방법은 [수많은 사이트](https://opentutorials.org/course/2418)에서 알려드리고 있으니 이를 참고해주세요.
