### ISSUE TITLE
에러와 함께 앱이 실행되지 않습니다

### ISSUE THREAD

**Issue by donghyeon0725** [joostory/tistory-editor#94]
![image](https://user-images.githubusercontent.com/57713239/128607124-5fae7a1f-47a2-4252-ab59-8c25d4ab79af.png)
위와 같은 에러가 나타나며 앱이 실행되지 않습니다.

**Comment by joostory** [comment]
1.4.2 버전에서 해결했습니다. 업데이트 하시면 문제 해결 될겁니다.

**Comment by shadekeys** [comment]
안녕하세요. 저는 1.4.2 버전 설치했는데 저런 에러 메시지가 뜹니다.

**Comment by joostory** [comment]
@donghyeon0725 @shadekeys 
https://github.com/joostory/tistory-editor/releases/tag/v1.4.3 에서 오류를 해결했습니다.
원인 파악을 잘못하고 있었네요. ㅠ 오랜시간 사용못하셨을텐데 죄송합니다.
