### ISSUE TITLE
1.4.2 최신버전 실행 시 오류

### ISSUE THREAD

**Issue by kisa002** [joostory/tistory-editor#95]
설치하고 바로 실행했음에도 오류가 발생합니다.
![image](https://user-images.githubusercontent.com/4679634/130351189-ef042cb8-092d-4e7e-ae49-88f32ff5a44f.png)

**Comment by joostory** [comment]
@kisa002 이제야 이 오류를 수정했습니다. 사용하는데 불편드려 죄송합니다. ㅠㅠ
